import { useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Destination = { id: string; platform: string; enabled: boolean; status: string };
type Stream = { id: string; name: string; status: string; createdAt: string; startedAt?: string; stoppedAt?: string; destinations: Destination[] };
type Created = Stream & { ingest: { server: string; streamKey: string } };
const api = async <T,>(url: string, options?: RequestInit): Promise<T> => {
  const request: RequestInit = { ...options };
  if (options?.body !== undefined) request.headers = { ...(options.headers ?? {}), 'Content-Type': 'application/json' };
  const response = await fetch(url, request);
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error ?? 'Request failed');
  return response.status === 204 ? undefined as T : response.json();
};
const navigate = (path: string) => { history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); };
const tone = (status: string) => status === 'LIVE' || status === 'CONNECTED' ? 'success' : status === 'FAILED' || status === 'ERROR' ? 'danger' : status === 'RECONNECTING' || status === 'CONNECTING' ? 'warning' : 'muted';

function Shell({ children }: { children: React.ReactNode }) {
  return <main><header><button className="brand" onClick={() => navigate('/dashboard')} aria-label="Cloud Restreamer home"><span>◉</span> CLOUD RESTREAMER</button><div className="header-status"><i /> Prototype mode</div></header>{children}</main>;
}
function Badge({ status }: { status: string }) { return <span className={`badge ${tone(status)}`}>{status.replace('_', ' ')}</span>; }
function Login() { return <Shell><section className="login"><div className="eyebrow">COLLEGE DEMONSTRATION</div><h1>One stream.<br /><em>Every audience.</em></h1><p>Send live video from OBS once, then route it through a single cloud ingestion point.</p><form onSubmit={(e) => { e.preventDefault(); navigate('/dashboard'); }}><label>Email<input type="email" required placeholder="student@college.edu" /></label><button>Enter dashboard <b>→</b></button></form><small>Prototype access — credentials are not stored.</small></section></Shell>; }
function Dashboard() {
  const [streams, setStreams] = useState<Stream[]>([]); const [error, setError] = useState('');
  useEffect(() => { api<Stream[]>('/api/streams').then(setStreams).catch(e => setError(e.message)); }, []);
  return <Shell><section className="page"><div className="hero"><div><div className="eyebrow">CONTROL ROOM</div><h1>Live streams</h1><p>Create a secure OBS ingest endpoint, then distribute from the cloud.</p></div><button onClick={() => navigate('/streams/new')}>+ New stream</button></div>{error && <div className="notice">API unavailable: {error}. Start the Docker stack, then refresh.</div>}<div className="stream-grid">{streams.length ? streams.map(stream => <button className="stream-card" key={stream.id} onClick={() => navigate(`/streams/${stream.id}`)}><div><Badge status={stream.status} /><span className="arrow">→</span></div><h2>{stream.name}</h2><p>{new Date(stream.createdAt).toLocaleString()}</p><footer>{stream.destinations.filter(d => d.enabled).length} destinations configured</footer></button>) : <div className="empty"><span>◉</span><h2>No streams yet</h2><p>Start with a named event to receive a private stream key.</p><button onClick={() => navigate('/streams/new')}>Create your first stream</button></div>}</div></section></Shell>;
}
function NewStream() {
  const [name, setName] = useState('College Event Demo'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const stream = await api<Created>('/api/streams', { method: 'POST', body: JSON.stringify({ name }) }); sessionStorage.setItem(`stream-key:${stream.id}`, JSON.stringify(stream.ingest)); navigate(`/streams/${stream.id}`); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create stream'); } finally { setBusy(false); } };
  return <Shell><section className="page narrow"><button className="back" onClick={() => navigate('/dashboard')}>← Back to streams</button><div className="eyebrow">NEW INGEST ENDPOINT</div><h1>Set up a live event</h1><p className="lead">The dashboard creates a cryptographically secure, one-time-visible stream key for OBS.</p><form className="panel form" onSubmit={submit}><label>Stream name<input value={name} onChange={e => setName(e.target.value)} required maxLength={80} /></label>{error && <div className="error">{error}</div>}<button disabled={busy}>{busy ? 'Creating…' : 'Create secure stream'} <b>→</b></button></form></section></Shell>;
}
function Detail({ id }: { id: string }) {
  const [stream, setStream] = useState<Stream | null>(null); const [error, setError] = useState(''); const [secretRefs, setSecretRefs] = useState<Record<string, string>>({});
  const load = () => api<Stream>(`/api/streams/${id}`).then(setStream).catch(e => setError(e.message));
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 5000); return () => clearInterval(timer); }, [id]);
  const ingest = JSON.parse(sessionStorage.getItem(`stream-key:${id}`) ?? 'null') as Created['ingest'] | null;
  const action = async (name: 'start' | 'stop') => { try { await api(`/api/streams/${id}/${name}`, { method: 'POST' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed'); } };
  const updateDestination = async (destination: Destination, enabled: boolean) => { try { await api(`/api/streams/${id}/destinations/${destination.id}`, { method: 'PUT', body: JSON.stringify({ enabled, secretReference: secretRefs[destination.id] || undefined }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Destination update failed'); } };
  if (error && !stream) return <Shell><section className="page"><div className="notice">{error}</div><button onClick={() => navigate('/dashboard')}>Back</button></section></Shell>;
  if (!stream) return <Shell><section className="page">Loading stream…</section></Shell>;
  return <Shell><section className="page"><button className="back" onClick={() => navigate('/dashboard')}>← Back to streams</button><div className="detail-head"><div><div className="eyebrow">STREAM CONTROL</div><h1>{stream.name}</h1><Badge status={stream.status} /></div><div className="actions">{['LIVE', 'CONNECTING'].includes(stream.status) ? <button className="danger-button" onClick={() => void action('stop')}>Stop stream</button> : <button onClick={() => void action('start')}>Arm for OBS <b>→</b></button>}</div></div>{error && <div className="notice">{error}</div>}<div className="two-col"><div className="panel"><div className="panel-title">OBS CONNECTION <span>01</span></div>{ingest ? <><label>RTMP server<div className="code">{ingest.server}</div></label><label>Stream key<div className="code key">{ingest.streamKey}</div></label><p className="hint">Copy this now. It is only retained in this browser session and is never returned by the API.</p></> : <div className="private"><b>Stream key hidden</b><p>For security, generated keys are shown only once — immediately after stream creation.</p></div>}</div><div className="panel"><div className="panel-title">INGEST STATUS <span>02</span></div><div className="status-orb"><i className={tone(stream.status)} /><div><strong>{stream.status === 'LIVE' ? 'Signal received' : 'Waiting for OBS'}</strong><p>{stream.status === 'LIVE' ? 'Cloud RTMP ingestion is active.' : 'Start OBS after arming this stream.'}</p></div></div><div className="architecture"><span>OBS</span><b>→</b><span>RTMP</span><b>→</b><span>Cloud</span></div></div></div><section className="destinations"><div className="section-title"><div><div className="eyebrow">DISTRIBUTION</div><h2>Destination routing</h2></div><p>Each platform runs independently. A failure retries without interrupting other live outputs.</p></div>{stream.destinations.map(d => <article className="destination" key={d.id}><div className="platform"><div className={`icon ${d.platform.toLowerCase()}`}>{d.platform === 'YOUTUBE' ? '▶' : d.platform === 'TWITCH' ? '◈' : 'in'}</div><div><h3>{d.platform[0] + d.platform.slice(1).toLowerCase()}</h3><Badge status={d.status} /></div></div><div className="secret"><label>AWS Secrets Manager reference<input value={secretRefs[d.id] ?? ''} onChange={e => setSecretRefs({ ...secretRefs, [d.id]: e.target.value })} placeholder="arn:aws:secretsmanager:…" aria-label={`${d.platform} secret reference`} /></label></div><label className="switch"><input type="checkbox" checked={d.enabled} onChange={e => void updateDestination(d, e.target.checked)} /><span /><b>{d.enabled ? 'Enabled' : 'Disabled'}</b></label></article>)}</section></section></Shell>;
}
function App() { const [path, setPath] = useState(location.pathname); useEffect(() => { const listener = () => setPath(location.pathname); addEventListener('popstate', listener); return () => removeEventListener('popstate', listener); }, []); if (path === '/login') return <Login />; if (path === '/streams/new') return <NewStream />; const match = path.match(/^\/streams\/([^/]+)$/); return match ? <Detail id={match[1]} /> : <Dashboard />; }
createRoot(document.getElementById('root')!).render(<App />);
